#!/bin/bash
#
# Check if you print enviroment (ONLY CHECKS IF YOU DO NOT THROWN ERROR XD)

command="env"

# clean up
stop_shell
rm -f $tmp_file

# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
if [ -s $ERROROUTPUTFILE ]; then
    print_ko
else
    print_ok_b
fi

# clean up
stop_shell
rm -f $tmp_file
