#!/bin/bash
#
# Check cd command

command="cd -"

# clean up
stop_shell
rm -f $tmp_file

# send commands

echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &
echo "$command" | /bin/sh > rightanswer 2> /dev/null &
# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
diff -q $OUTPUTFILE rightanswer
match=$?
if [ $match -eq 0 ]; then
    print_ok_b
else
    print_ko
fi

# clean up
stop_shell
rm -f $OUTPUTFILE
rm -f $tmp_file
rm -f rightanswer.
