#!/bin/bash
#
# Check if not found error is correct

command="qwerty"

# clean up
stop_shell
rm -f $tmp_file

# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS


# check the result
echo "$SHELL: 1: qwerty: not found" > your_output
diff -q $ERROROUTPUTFILE your_output
match=$?
if [ $match -eq 0 ]; then
    print_ok
else
    print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
rm -f your_output
