#!/bin/bash
#
# Just check if help runs

command="help"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file

# send commands
echo "$command" | $SHELL > /dev/null 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
echo "$SHELL: 1: help: not found" > answer
diff -q $ERROROUTPUTFILE answer
match=$?
if [ $match -eq 0 ]; then
    print_ok
else
    print_ko
fi


# clean up
stop_shell
rm -f $tmp_file
rm -f answer
